// Package main bootstraps the yy-kitchen-logic HTTP server.
//
// @title           YY Kitchen Logic API
// @version         1.0
// @description     Internal API server for yy-kitchen-logic.
// @host            localhost:8090
// @BasePath        /
// @securityDefinitions.apikey BearerAuth
// @in              header
// @name            Authorization
package main

import (
	"log"
	"net/http"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"yy-kitchen-logic/config"
	"yy-kitchen-logic/db"
	"yy-kitchen-logic/models"
	"yy-kitchen-logic/routes"

	_ "yy-kitchen-logic/docs" // generated by swag init
)

// scalarHTML renders the Scalar API reference UI, loading the spec
// produced by swag from /swagger/doc.json.
const scalarHTML = `<!doctype html>
<html>
  <head>
    <title>YY Kitchen Logic API</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <script id="api-reference" data-url="/swagger/doc.json"></script>
    <script>
      var configuration = { theme: 'purple' };
      document.getElementById('api-reference').dataset.configuration =
        JSON.stringify(configuration);
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>`

func main() {
	cfg := config.Load()
	gin.SetMode(cfg.App.Mode)

	conn := db.Init(cfg.Database.Path, &models.User{})

	r := gin.Default()

	// Swagger spec endpoints (kept for tooling that consumes /swagger/doc.json)
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Modern UI powered by Scalar, reading the same spec.
	r.GET("/docs", func(c *gin.Context) {
		c.Data(http.StatusOK, "text/html; charset=utf-8", []byte(scalarHTML))
	})

	routes.Register(r, conn, *cfg)

	addr := ":" + cfg.App.Port
	log.Printf("server starting on %s (docs at %s/docs, swagger at %s/swagger/index.html)", addr, addr, addr)
	if err := r.Run(addr); err != nil {
		log.Fatalf("server failed: %v", err)
	}
}
